### ISSUE TITLE
デザイン２パターンの方針決め

### ISSUE THREAD

**Issue by ForDevelopment** [KSKAnalyticsInc/test#1]
TOPページに置こうと思っている各メニューとWORKS画像の構成案を２パターン作って比較したいと思います。

TODO

- [ ] パターンA
- [ ] パターンB

**Comment by ForDevelopment2** [comment]
マークダウンは**Previewタグ**で確認できます。

**Comment by ForDevelopment** [comment]
ヘッダーとフッターはどうしましょうか？
