### ISSUE TITLE
横スライドショー版デザイン

### ISSUE THREAD

**Issue by ForDevelopment2** [KSKAnalyticsInc/test#2]
ヘッダーにロゴ、WORKSの画像は大きく横に動くスライドショーにする。メニューを下部に並べて用意するデザイン。

**Comment by ForDevelopment2** [comment]
![image2](https://cloud.githubusercontent.com/assets/13672170/9433239/93dd311c-4a6a-11e5-85d8-fc56654544d4.png)

**Comment by ForDevelopment2** [comment]
@KSKAnalyticsInc/admin 　修正したので、確認してください。

**Comment by ForDevelopment** [comment]
@ForDevelopment2 ありがとうございます。　

確認します。
