### ISSUE TITLE
デザイン決定

### ISSUE THREAD

**Issue by ForDevelopment** [KSKAnalyticsInc/test#4]
パターンA #3 とパターンB #2 のデザインを比較して最終的にどちらのデザインにするかを決定しましょう。
皆さんの意見を聞かせて下さい。

**Comment by ForDevelopment2** [comment]
#3 の方がシンプルで良いですね。

**Comment by ForDevelopment** [comment]
#2 の方が面白いですね。

**Comment by ForDevelopment** [comment]
ということで、 #2 を採用します。
